language: node_js

node_js:
    - 12

matrix:
    include:
    - os: linux
        dist: xenial
        sudo: required
    - os: osx
    - os: windows

cache:
    npm: true

notifications:
    email: false

script:
    - npm run build && npm run electron-pack